# Generated by Django 3.2 on 2022-01-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_customerprofile_default_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='default_email',
        ),
    ]
