# Generated by Django 3.2 on 2022-01-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_customerprofile_default_email'),
        ('reviews', '0002_auto_20220121_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.customerprofile'),
        ),
    ]
