# Generated by Django 3.2 on 2022-01-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('till', '0002_auto_20220111_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
