# Generated by Django 3.2 on 2022-01-14 17:19

from django.db import migrations, models
import till.models


class Migration(migrations.Migration):

    dependencies = [
        ('till', '0003_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, validators=[till.models.Order.validate_delivery_date]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
