# Generated by Django 3.2 on 2022-01-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('till', '0004_auto_20220114_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
