# Generated by Django 3.2 on 2021-12-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_quantity_product_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lunch_deal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option_grilled',
        ),
    ]
