# Generated by Django 3.2 on 2021-12-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211231_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lunch_deal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option_grilled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
