# Generated by Django 3.2 on 2021-12-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211231_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
