# Generated by Django 3.2 on 2022-01-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220102_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calory_count',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
