# Generated by Django 3.2 on 2022-01-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_has_gluten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calory_count',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
