# Generated by Django 3.2 on 2022-01-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_calory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calory_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
