# Generated by Django 3.2 on 2022-01-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_calory_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='calory_count',
            new_name='calory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='has_gluten',
            new_name='gluten',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_vegan',
            new_name='vegan',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_vegetarian',
            new_name='vegetarian',
        ),
    ]
