# Generated by Django 3.2 on 2022-01-18 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_auto_20220117_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
