# Generated by Django 3.2 on 2022-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_favourite_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='is_fav',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
