# Generated by Django 3.2 on 2022-01-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_favourite_is_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourites',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
